[package]
name = "yewoh-bevy-client"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_egui = "0.20.2"
bevy_reflect_derive = "0.10.0"
bevy_prototype_debug_lines = "0.10.1"
bevy-inspector-egui = "0.18.1"
serde = "1.0.158"
serde_derive = "1.0.158"
serde_json = "1.0.95"
anyhow = "1.0.70"
futures = "0.3.27"
rand = "0.8.5"
egui = "0.21.0"

[dependencies.bevy]
version = "0.10.0"
default-features = false
features = [
    "animation",
    "bevy_asset",
    "bevy_gilrs",
    "bevy_render",
    "bevy_scene",
    "bevy_winit",
    "png",
    "hdr",
    "filesystem_watcher",
    "x11"
]

[dependencies.bevy_kira_audio]
version = "0.15.0"
default-features = false
features = [
    "wav",
    "flac",
    "mp3",
    "ogg",
]

[features]
debug = ["bevy/dynamic_linking"]
