[package]
name = "yewoh-bevy-client"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_egui = "0.15.0"
bevy_reflect_derive = "0.8.1"
bevy_prototype_debug_lines = "0.8.1"
bevy-inspector-egui = "0.12.1"
iyes_loopless = "0.7.0"
serde = "1.0.141"
serde_derive = "1.0.141"
serde_json = "1.0.82"
anyhow = "1.0.59"
futures = "0.3.21"
rand = "0.8.5"
egui = "0.18.1"

[dependencies.bevy]
version = "0.8.1"
default-features = false
features = [
    "render",
    "animation",
    "bevy_asset",
    "bevy_scene",
    "bevy_winit",
    "bevy_gilrs",
    "png",
    "hdr",
    "filesystem_watcher",
    "x11"
]

[dependencies.bevy_kira_audio]
version = "0.11"
default-features = false
features = [
    "wav",
    "flac",
    "mp3",
    "ogg",
]

[features]
debug = ["bevy/dynamic"]
