[package]
name = "yewoh-default-game"
description = "A server implementation of Ultima Online"
authors = ["Erica Sian Taylor"]
repository = "https://github.com/ricky26/yewoh"
license = "MIT"
version = "0.1.0"
edition = "2021"

[dependencies]
yewoh = { path = "../core" }
yewoh-server = { path = "../server" }
tokio = { version = "1.21.0", default_features = false, features = ["fs", "net", "macros"] }
futures = "0.3.24"
anyhow = "1.0.64"
log = "0.4.17"
clap = "3.2.20"
async-trait = "0.1.57"
bevy_ecs = "0.8.1"
bevy_app = "0.8.1"
glam = "0.21.3"
serde = "1.0.144"
serde_derive = "1.0.144"
serde_yaml = "0.9.11"
shell-words = "1.1.0"
chrono = "0.4.22"
