[package]
name = "yewoh-default-game"
version = "0.1.0"
edition = "2021"

[dependencies]
yewoh = { path = "../core" }
yewoh-server = { path = "../server" }
tokio = { version = "1.21.0", default_features = false, features = ["net"] }
log = "0.4.17"
bevy_ecs = "0.8.1"
bevy_app = "0.8.1"
glam = "0.21.3"
quadtree_rs = "0.1.2"
