[package]
name = "yewoh-server"
description = "A server implementation of Ultima Online"
authors = ["Erica Sian Taylor"]
repository = "https://github.com/ricky26/yewoh"
license = "MIT"
version = "0.1.0"
edition = "2021"

[dependencies]
yewoh = { path = "../core" }
tokio = { version = "1.26.0", default_features = false, features = ["net"] }
futures = "0.3.27"
anyhow = "1.0.70"
async-trait = "0.1.68"
log = "0.4.17"
bevy_ecs = "0.10.0"
bevy_app = "0.10.0"
bevy_reflect = "0.10.0"
glam = "0.23.0"
rstar = "0.10.0"
bitflags = "2.0.2"
